server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-microservice
          uri: lb://user-microservice
          predicates:
            - Path=/users/**
        - id: car-microservice
          uri: lb://car-microservice
          predicates:
            - Path=/cars/**
        - id: bike-microservice
          uri: lb://bike-microservice
          predicates:
            - Path=/bikes/**
        - id: auth-microservice
          uri: lb://auth-microservice
          predicates:
            - Path=/auth/**
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            authorization-uri: http://localhost:8180/realms/tutorial-realm/protocol/openid-connect/auth
#            userinfo-uri: http://localhost:8180/realms/tutorial-realm/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username
#            token-uri: http://localhost:8180/realms/tutorial-realm/protocol/openid-connect/token
#        registration:
#          tutorial-client:
#            provider: keycloak
#            client-id: tutorial-client
#            client-secret: oOnxtNUgFZSIVKtqoU8Pum93oARJc7Ak
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/tutorial-client"